# Generated by Django 3.1.7 on 2021-04-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('image', models.ImageField(upload_to='covers', verbose_name='Book Cover')),
                ('genre', models.CharField(max_length=350, verbose_name='Genre')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='HardBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LibrarySystem.book')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
            ],
            bases=('LibrarySystem.book',),
        ),
        migrations.CreateModel(
            name='SoftBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LibrarySystem.book')),
                ('book', models.FileField(upload_to='books', verbose_name='Book')),
            ],
            bases=('LibrarySystem.book',),
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('returned', models.BooleanField(null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibrarySystem.book')),
            ],
        ),
    ]
